#Autor: Claudio Aliste R- Ingeniero de Infraestructura TI & Cloud
#email: aliste.claudio@gmail.com
#version: 2.1
#
#Disclaimer: si le generan una mejora al archivo favor enviar para actualizar en los repositorios, poner comentarios acá abajo con la mejora y sus datos de contacto.
#
#
#
#
#
#
#

version: '3.7'

services:
  # Servicio Traefik
  traefik:
    image: traefik:v2.2
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tu-email@ejemplo.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Habilita la API de Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

  # Servicio Geinet
  geinet:
    image: nginx:alpine
    container_name: geinet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geinet.rule=Host(`geinet.cl`)"
      - "traefik.http.routers.geinet.entrypoints=websecure"
      - "traefik.http.routers.geinet.tls.certresolver=myresolver"
      - "traefik.http.middlewares.geinet-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.geinet.middlewares=geinet-redirect"
    networks:
      - web
    volumes:
      - ./geinet/index.html:/usr/share/nginx/html/index.html

  # Servicio ChileFPV
  chilefpv:
    image: nginx:alpine
    container_name: chilefpv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chilefpv.rule=Host(`chilefpv.cl`)" #aca debemos editar el nombre del dominio que se bucsara, gunto con todo los nombres indicando dominio correcto
      - "traefik.http.routers.chilefpv.entrypoints=websecure"
      - "traefik.http.routers.chilefpv.tls.certresolver=myresolver"
      - "traefik.http.middlewares.chilefpv-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.chilefpv.middlewares=chilefpv-redirect"
    networks:
      - web
    volumes:
      - ./chilefpv/index.html:/usr/share/nginx/html/index.html

  # Servicio para el subdominio
  sitio1:
    image: nginx:alpine
    container_name: sitio1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sitio1.rule=Host(`sitio1.chilefpv.cl`)" #este es el caso agregar wildcard a la confiuracion
      - "traefik.http.routers.sitio1.entrypoints=websecure"
      - "traefik.http.routers.sitio1.tls.certresolver=myresolver"
      - "traefik.http.middlewares.sitio1-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sitio1.middlewares=sitio1-redirect"
    networks:
      - web
    volumes:
      - ./sitio1/index.html:/usr/share/nginx/html/index.html  #las ptimeras lineas indican nombre de carpeta y el archivo que se cargara en el contenedor

networks:
  web:
    external: true
